url: "https://dpstrange.github.io/jekyll-piratesec"
baseurl: ""
permalink: /:title/

title: "PirateSec"
subtitle: "A Seapunk Falvored Retro Terminal Jekyll Theme"
description: "A Seapunk falvored Jekyll theme inspired by retro terminals."

# pixelate.js - class="pixelate", pixelateAll overides all settings
pixelateFeatured: true # pixelate all header images
pixelateAll: false # pixelate all images